import { type Commission } from './db';
import * as htmlToImage from 'html-to-image';

export type ExportFormat = 'json' | 'whatsapp' | 'png';

export interface ExportOptions {
  format: ExportFormat;
  elementId?: string; // For PNG export
  filename?: string; // For JSON export
}

export class DataExporter {
  static async exportToJSON(commissions: Commission[], filename = 'dnzwrk-commissions.json'): Promise<void> {
    try {
      const dataStr = JSON.stringify(commissions, null, 2);
      const blob = new Blob([dataStr], { type: 'application/json' });
      const url = URL.createObjectURL(blob);

      const link = document.createElement('a');
      link.href = url;
      link.download = filename;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Failed to export JSON:', error);
      throw new Error('Failed to export data to JSON');
    }
  }

  static async exportToWhatsApp(commissions: Commission[]): Promise<void> {
    try {
      const stats = this.calculateStats(commissions);
      const message = this.formatWhatsAppMessage(stats, commissions);

      const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(message)}`;
      window.open(whatsappUrl, '_blank');
    } catch (error) {
      console.error('Failed to export to WhatsApp:', error);
      throw new Error('Failed to share via WhatsApp');
    }
  }

  static async exportToPNG(elementId: string, filename = 'dnzwrk-dashboard.png'): Promise<void> {
    try {
      const element = document.getElementById(elementId);
      if (!element) {
        throw new Error('Dashboard element not found');
      }

      const dataUrl = await htmlToImage.toPng(element, {
        quality: 0.95,
        backgroundColor: '#ffffff'
      });

      const link = document.createElement('a');
      link.download = filename;
      link.href = dataUrl;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } catch (error) {
      console.error('Failed to export PNG:', error);
      throw new Error('Failed to export dashboard as image');
    }
  }

  private static calculateStats(commissions: Commission[]) {
    const total = commissions.reduce((sum, commission) => sum + commission.amount, 0);
    const pending = commissions
      .filter(c => c.status === 'pending')
      .reduce((sum, commission) => sum + commission.amount, 0);
    const completed = commissions
      .filter(c => c.status === 'completed')
      .reduce((sum, commission) => sum + commission.amount, 0);

    return {
      total,
      pending,
      completed,
      count: commissions.length,
      pendingCount: commissions.filter(c => c.status === 'pending').length,
      completedCount: commissions.filter(c => c.status === 'completed').length
    };
  }

  private static formatWhatsAppMessage(stats: any, commissions: Commission[]): string {
    const message = `
📊 *DNZwrk CRM Summary*

💰 *Total Commissions:* ${stats.count}
💵 *Total Amount:* $${stats.total.toFixed(2)}

📈 *Status Breakdown:*
✅ Completed: ${stats.completedCount} ($${stats.completed.toFixed(2)})
⏳ Pending: ${stats.pendingCount} ($${stats.pending.toFixed(2)})

📝 *Recent Commissions:*
${commissions.slice(0, 5).map(c =>
  `• ${c.title} - ${c.client} - $${c.amount.toFixed(2)} (${c.status})`
).join('\n')}

---
Generated by DNZwrk CRM - Your Personal Commission Tracker
    `.trim();

    return message;
  }

  static async handleExport(commissions: Commission[], options: ExportOptions): Promise<void> {
    switch (options.format) {
      case 'json':
        await this.exportToJSON(commissions, options.filename);
        break;
      case 'whatsapp':
        await this.exportToWhatsApp(commissions);
        break;
      case 'png':
        if (!options.elementId) {
          throw new Error('Element ID is required for PNG export');
        }
        await this.exportToPNG(options.elementId, options.filename);
        break;
      default:
        throw new Error(`Unsupported export format: ${options.format}`);
    }
  }
}